export enum AuthByLoginAndPasswordErrorType {
  EMAIL_EMPTY = 'EMAIL_EMPTY',
  PASSWORD_EMPTY = 'PASSWORD_EMPTY',
  EMAIL_IS_NOT_CORRECT = 'EMAIL_IS_NOT_CORRECT',
  AUTHORIZATION_FAILED = 'authorizationFailed',
  PASSWORD_NOT_SET = 'passwordNotSet',
  SERVER_ERROR = 'Server Error',
  NETWORK_ERROR = 'NETWORK_ERROR'
}
