image: docker:latest

services:
- docker:dind

variables:
  REGISTRY: registry.redmadrobot.com:5005
  NPM_REGISTRY: https://nexus.redmadrobot.com/repository/npm-group/
  GROUP: web-frontend
  PROJECT: ts-boilerplate
  IMAGE: ${REGISTRY}/${GROUP}/${PROJECT}

stages:
  - build
  - test
  - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY

build_image:
  stage: build
  script:
    - docker build
      --build-arg auth=${CI_NPM_AUTH}
      --build-arg registry=${NPM_REGISTRY}
      -t ${IMAGE}:rc-${CI_COMMIT_REF_NAME} .
    - docker push ${IMAGE}:rc-${CI_COMMIT_REF_NAME}
  when: always
  tags:
    - frontend-docker

test_lint:
  stage: test
  script:
    - docker pull ${IMAGE}:rc-${CI_COMMIT_REF_NAME}
    - docker run ${IMAGE}:rc-${CI_COMMIT_REF_NAME} npm run lint
  when: on_success
  tags:
    - frontend-docker

test_unit:
  stage: test
  script:
    - docker pull ${IMAGE}:rc-${CI_COMMIT_REF_NAME}
    - docker run ${IMAGE}:rc-${CI_COMMIT_REF_NAME} npm t
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  when: on_success
  tags:
    - frontend-docker

release:
  stage: release
  script:
    - docker tag ${IMAGE}:rc-${CI_COMMIT_REF_NAME} ${IMAGE}:${CI_COMMIT_REF_NAME}
    - docker push ${IMAGE}:${CI_COMMIT_REF_NAME}
  only:
    - master
    - dev
  when: on_success
  tags:
    - frontend-docker
