files:
  include: 'app/**/*.sass'
rules:
  attribute-quotes:
    - 2
    -
      include: false
  bem-depth:
    - 2
    -
      max-depth: 1
  border-zero:
    - 2
    -
      convention: '0'
  class-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'strictbem'
  declarations-before-nesting: 2
  empty-args:
    - 2
    -
      include: false
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 0
  final-newline:
    - 2
    -
      include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  hex-length:
    - 2
    -
      style: short
  hex-notation:
    - 2
    -
      style: 'lowercase'
  id-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: false
  max-file-line-count:
    - 2
    -
      length: 150
  max-line-length:
    - 2
    -
      length: 50
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  mixins-before-declarations: 0
  nesting-depth:
    - 2
    -
      max-depth: 3
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-ids: 0
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
  no-trailing-whitespace: true
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols:
    - 2
    -
      allow-protocol-relative-urls: false
  no-vendor-prefixes: 0
  no-warn: 2
  one-declaration-per-line: 2
  property-sort-order:
    - 2
    -
      order: 'concentric'
      ignore-custom-properties: false
  pseudo-element: 2
  quotes:
    - 2
    -
      style: 'double'
  single-line-per-selector: 2
  space-after-colon:
    - 2
    -
      include: true
  space-after-comma:
    - 2
    -
      include: true
  space-around-operator:
    - 2
    -
      include: true
  url-quotes: 2
  variable-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  zero-unit:
    - 2
    -
      include: false
